version: "3"

services:
  mongo: #our mongoDB instance that will hold post data
    image: mongo
    restart: unless-stopped
    environment:
    #if using this repo as base, remember to change those credentials!
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "dbdata:/data/db" #use volumes for persisting data

  mongo-express: #mongo admin access
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081 #IMPORTANT: deploy on not forwarded port to avoid unauthorized access
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    depends_on:
      - mongo


  web: #our NGINX instance that will serve website and will expose API service
    build:
      context: ./personal_site
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      

  api: #our ASP CORE Api
      build: ./Api
      restart: unless-stopped
      
volumes:
  dbdata:
    driver: local
  certbot-etc:
  certbot-var:
  web-root:
