version: "3"

services:
  mongo: #our mongoDB instance that will hold post data
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express: #mongo admin access
    image: mongo-express
    restart: always
    ports:
      - 8081:8081 #IMPORTANT: deploy on not forwarded port to avoid unauthorized access
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo


  web: #our NGINX instance that will serve website and will expose API service
    image: nginx
    build: ./nginx_confs
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


    
